paths:
  archive_dir: archive
  changes_dir: changes
  platforms_dir: .stdd/platforms
  skills_dir: .stdd/skills
  specs_dir: specs
  standards_dir: .stdd/standards
  templates_dir: .stdd/templates
project:
  language: python
  name: stdd
  python_version: '3.10'
  source_dir: "app"
stdd_version: '2.0'
