"""stdd ci — Generate CI/CD config files and run deterministic failure checks."""
import argparse
import sys
import re
from pathlib import Path
from datetime import datetime



GITHUB_WORKFLOW_TEMPLATE = """\
# STDD Quality Gate — Auto-generated by `stdd ci init`
# Version: {version}
# Generated: {date}

name: STDD Quality Gate

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  stdd-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff

      - name: STDD Validate
        run: python bin/stdd validate

      - name: Run Tests with Coverage
        run: {test_command}

      - name: STDD Diff Check
        run: python bin/stdd diff

      - name: Lint Check
        run: {lint_command}

      - name: Type Check
        run: {typecheck_command}

      - name: STDD Failure Check
        run: python bin/stdd ci check-failures
"""

PRECOMMIT_TEMPLATE = """\
# STDD Pre-commit Hook — Auto-generated by `stdd ci init`
# Version: {version}
# Generated: {date}

repos:
  - repo: local
    hooks:
      - id: stdd-validate
        name: STDD Validate
        entry: python bin/stdd validate
        language: system
        pass_filenames: false
        stages: [commit]

      - id: stdd-lint
        name: STDD Lint
        entry: {lint_command}
        language: system
        pass_filenames: false
        types: [python]
        stages: [commit]
"""

PR_COMMENT_TEMPLATE = """\
## STDD Quality Gate Results

| Check | Status | Details |
|-------|--------|---------|
| Validate | {{{{ validate }}}} | Structure & spec format check |
| Tests | {{{{ tests }}}} | {{{{ test_summary }}}} |
| Coverage | {{{{ coverage }}}}% | Target: {{{{ coverage_target }}}}% |
| Diff | {{{{ diff }}}} | Spec ↔ Test ↔ Code traceability |
| Lint | {{{{ lint }}}} | Code style check |
| Failure Check | {{{{ failures }}}} | 11 failure modes (deterministic subset) |

{ {{{ failure_details}}} }

---
📋 [Full Test Report]({{{{ test_report_url }}}}) · 📝 [Design Adjustments]({{{{ adjustments_url }}}})
"""


def _read_quality_config(project_root: Path) -> dict:
    """Read quality.yaml config."""
    from ..utils import read_config
    return read_config(project_root)


def _generate_workflow(project_root: Path, config: dict, dry_run: bool = False) -> str:
    ci_cfg = config.get("ci", {}).get("github_actions", {})
    python_version = ci_cfg.get("python_version", config.get("project", {}).get("python_version", "3.11"))
    test_cmd = ci_cfg.get("test_command", "pytest tests/ --cov=app --cov-report=xml --cov-report=term")
    lint_cmd = ci_cfg.get("lint_command", "ruff check app/ tests/")
    typecheck_cmd = ci_cfg.get("typecheck_command", "mypy app/")

    content = GITHUB_WORKFLOW_TEMPLATE.format(
        version="2.4",
        date=datetime.now().strftime("%Y-%m-%d"),
        python_version=python_version,
        test_command=test_cmd,
        lint_command=lint_cmd,
        typecheck_command=typecheck_cmd,
    )

    workflow_dir = project_root / ".github" / "workflows"
    workflow_path = workflow_dir / "stdd-quality.yml"

    if dry_run:
        print(f"\n  [DRY-RUN] 将创建: {workflow_path}")
        print("  ──────────────────────────────────────")
        print(content)
        return content

    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(content, encoding="utf-8")
    print(f" 已创建: {workflow_path}")
    return content


def _generate_precommit(project_root: Path, config: dict, dry_run: bool = False) -> str:
    lint_cmd = config.get("quality", {}).get("lint", "ruff check app/ tests/")

    content = PRECOMMIT_TEMPLATE.format(
        version="2.4",
        date=datetime.now().strftime("%Y-%m-%d"),
        lint_command=lint_cmd,
    )

    precommit_path = project_root / ".pre-commit-config.yaml"

    if dry_run:
        print(f"\n  [DRY-RUN] 将创建: {precommit_path}")
        print("  ──────────────────────────────────────")
        print(content)
        return content

    if precommit_path.exists():
        existing = precommit_path.read_text(encoding="utf-8")
        if "STDD" in existing:
            print("  检测到已有 STDD pre-commit hook，跳过生成（避免覆盖现有配置）。")
            print("  如需重新生成，请先手动删除 .pre-commit-config.yaml 中的 STDD 段。")
            return content

        print("  检测到已有 .pre-commit-config.yaml，追加 STDD hook 段...")
        with open(precommit_path, "a", encoding="utf-8") as f:
            f.write("\n" + content)
        print(f" 已追加到: {precommit_path}")
        return content

    precommit_path.write_text(content, encoding="utf-8")
    print(f" 已创建: {precommit_path}")
    return content


def _generate_pr_template(project_root: Path, config: dict, dry_run: bool = False) -> str:
    github_dir = project_root / ".github"
    pr_path = github_dir / "stdd-pr-comment.md"

    if dry_run:
        print(f"\n  [DRY-RUN] 将创建: {pr_path}")
        print("  ──────────────────────────────────────")
        print(PR_COMMENT_TEMPLATE)
        return PR_COMMENT_TEMPLATE

    github_dir.mkdir(parents=True, exist_ok=True)
    pr_path.write_text(PR_COMMENT_TEMPLATE, encoding="utf-8")
    print(f" 已创建: {pr_path}")
    return PR_COMMENT_TEMPLATE


def _cmd_generate(args: argparse.Namespace, project_root: Path, config: dict) -> None:
    target = args.target
    dry_run = getattr(args, "dry_run", False)

    if target == "workflow":
        _generate_workflow(project_root, config, dry_run)
    elif target == "pre-commit":
        _generate_precommit(project_root, config, dry_run)
    elif target == "pr-template":
        _generate_pr_template(project_root, config, dry_run)
    else:
        print(f" 未知目标: {target}. 可用: workflow, pre-commit, pr-template")


def _cmd_init(args: argparse.Namespace, project_root: Path, config: dict) -> None:
    dry_run = getattr(args, "dry_run", False)
    print()
    if dry_run:
        print(" [DRY-RUN 模式] 预览将要创建的文件:\n")

    _generate_workflow(project_root, config, dry_run)
    _generate_precommit(project_root, config, dry_run)
    _generate_pr_template(project_root, config, dry_run)

    if dry_run:
        print("\n [DRY-RUN] 以上为预览，未实际创建任何文件。")
        print(" 去掉 --dry-run 以实际生成。")
    else:
        print()
        print(" STDD CI/CD 配置生成完成！")
        print(" 下一步：")
        print("   git add .github/ .pre-commit-config.yaml")
        print("   git commit -m 'chore: add STDD quality gate CI'")


def _cmd_check_failures(args: argparse.Namespace, project_root: Path) -> None:
    from ..finder import find_change_dir

    change_dir = find_change_dir(getattr(args, "name", None), project_root)
    if change_dir is None:
        print(f" 找不到 change: {getattr(args, 'name', None) or '(无)'}")
        sys.exit(1)

    errors = []
    warnings = []
    passed = []

    # Check files exist
    for f in ["proposal.md", "design.md", "test-plan.md", ".stdd.yaml"]:
        if (change_dir / f).exists():
            passed.append(f"(a) 文件存在: {f}")
        else:
            errors.append(f"(a) 缺失文件: {f}")

    # Check spec format
    specs_dir = change_dir / "specs"
    if specs_dir.exists():
        has_spec = any(specs_dir.rglob("*.md"))
        if has_spec:
            passed.append("(a) Spec 文件存在")
        else:
            warnings.append("(a) specs 目录为空")

        for spec_file in specs_dir.rglob("*.md"):
            content = spec_file.read_text(encoding="utf-8")
            scenarios = re.findall(r"####\s+Scenario:", content)
            then_lines = re.findall(r"\*\*THEN\*\*\s*(.+?)(?:\n|$)", content)
            and_count = len(re.findall(r"\*\*AND\*\*", content))

            if len(scenarios) > 0:
                no_shall = [t for t in then_lines if "SHALL" not in t]
                if no_shall:
                    warnings.append(f"(f) {spec_file.name}: {len(no_shall)} 个 THEN 缺少 SHALL")
                else:
                    passed.append(f"(f) {spec_file.name}: 所有 THEN 含 SHALL")

                if and_count > 5:
                    warnings.append(f"(g) {spec_file.name}: AND 数量 ({and_count}) 超限")
                else:
                    passed.append(f"(g) {spec_file.name}: AND 数量正常 ({and_count})")

    # Check TC-ID uniqueness
    test_plan = change_dir / "test-plan.md"
    if test_plan.exists():
        content = test_plan.read_text(encoding="utf-8")
        tc_ids = re.findall(r"(TC-[A-Z]+-\d{3})", content)
        if tc_ids:
            duplicates = [tc for tc in tc_ids if tc_ids.count(tc) > 1]
            if duplicates:
                errors.append(f"(d) 重复 TC-ID: {set(duplicates)}")
            else:
                passed.append(f"(d) TC-ID 唯一性: {len(set(tc_ids))} 个唯一")
            passed.append(f"(j) TC 数量: {len(set(tc_ids))}")

    # Check scope creep (files in change match proposal expectations)
    passed.append("(b) 范围检查: 请使用 /stdd-verify 进行 AI 全量检查")

    print()
    print("  STDD 失败模式检查结果 (CLI 确定性子集)")
    print(f"  {'─' * 50}")
    print(f"  ✅ 通过: {len(passed)}")
    print(f"  ⚠ 警告: {len(warnings)}")
    print(f"  ❌ 错误: {len(errors)}")

    if passed:
        print("\n  通过项:")
        for p in passed:
            print(f"    ✓ {p}")
    if warnings:
        print("\n  警告项:")
        for w in warnings:
            print(f"    ⚠ {w}")
    if errors:
        print("\n  错误项:")
        for e in errors:
            print(f"    ✗ {e}")

    print("\n  ──────────────────────────────────────")
    print("  确定性检查覆盖约 60% 的失败模式。")
    print("  未覆盖: (c)级联错误, (e)工具误用, (h)内容质量偏差, (i)指令衰减, (k)契约断层")
    print("  完整 11 类检查（含语义分析）请使用 /stdd-verify")
    print()

    if errors:
        sys.exit(1)


def cmd_ci(args: argparse.Namespace) -> None:
    from ..utils import get_logger
    get_logger()

    project_root = Path.cwd()

    subcommand = args.subcommand if getattr(args, "subcommand", None) else "init"

    if subcommand == "init":
        config = _read_quality_config(project_root)
        _cmd_init(args, project_root, config)
    elif subcommand in ("generate", "gen"):
        config = _read_quality_config(project_root)
        _cmd_generate(args, project_root, config)
    elif subcommand == "check-failures":
        _cmd_check_failures(args, project_root)
    else:
        print(f" 未知子命令: {subcommand}")
        print(" 可用: init, generate, check-failures")
        sys.exit(1)
